# worker_processes is a directive which tells us how many parallel process a server will create for handling client request
# here "worker_processes 1" the number represents only one process to spawn and also can be set to auto which means it will create process on the basic of CPU cores.
worker_processes 1;

events {
# worker_connections handles 1024 request at once per process i.e. set to 1
# higher the number more request it handles, downside: more cpu usage.
    worker_connections 1024;
}

http {
# for images and files
    include mime.types;

#upstream with app name means from client --> to --> server.
#downstream means from server --> to --> client.
    upstream skill_app_server {
    #which algo to use for server like: round robin, least connections etc.
        least_conn;
        server 127.0.0.1:8181;
        server 127.0.0.1:8182;
        server 127.0.0.1:8183;
    }

# basic server configuration
    server {
        listen 443 ssl;
        # listen 8080;
        server_name localhost;

        ssl_certificate C:/Users/dk904/Downloads/skillmatrix/skillmatrix/nginx-cert/nginx-selfsigned.crt;
        ssl_certificate_key C:/Users/dk904/Downloads/skillmatrix/skillmatrix/nginx-cert/nginx-selfsigned.key;

        location / {
            proxy_pass http://skill_app_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # auto redirect to https even the user type http:// or just url
    server {
        listen 8080;
        server_name localhost;

        location / {
            return 301 https://$host$request_uri;
        }
    }
}

