server:
    port: ${PORT:8181}
    servlet:
        context-path: /

spring:
    application:
        name: skillMatrix
    jpa:
        hibernate:
            ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
        show-sql: true
        database: postgresql
        generate-ddl: true
    datasource:
        url: jdbc:postgresql://localhost:5433/skillMatrix
        username: postgres
        password: d3kumar
        driverClassName: org.postgresql.Driver
    sql:
        init:
            platform: postgres

springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
