server:
    port: ${PORT:8181}
    cors:
        enabled: true
    servlet:
        context-path: /skillMatrix

spring:
    application:
        name: skillMatrix
    jpa:
        hibernate:
            ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
        show-sql: true
        database: postgresql
        generate-ddl: true
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/skillMatrix
        username: postgres
        password: password
        driverClassName: org.postgresql.Driver

swagger:
    path: http://localhost:8181/skillMatrix/v3/api-docs


