spring:
    application:
        server: 8080
        name: skillMatrix

    jpa:
        hibernate:
            ddl-auto: update  # Example of an additional property you might need
        show-sql: true      # Example to show SQL queries in the console
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5433/skillMatrix
        username: postgres
        password: d3kumar
        driverClassName: org.postgresql.Driver


